### ISSUE TITLE
Error in Blender 2.90

### ISSUE THREAD

**Issue by kirejam** [Ben-Norris/Random-Shapes#14]
Hi! I was impressed by your addon and wanted to try it, so I set up a simple scene with a camera and an ico-sphere and then selected it and clicked the "generate random shapes!" button, but an error ocurred:

**Traceback (most recent call last):
  File "/Users/kirejam/Library/Application Support/Blender/2.90/scripts/addons/Random-Shapes-master/__init__.py", line 243, in execute
    generate_shapes(self, context)
  File "/Users/kirejam/Library/Application Support/Blender/2.90/scripts/addons/Random-Shapes-master/__init__.py", line 121, in generate_shapes
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier="Edge Split")
  File "/Applications/Blender.app/Contents/Resources/2.90/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1**

is there anything I can do to fix it?

**Comment by Ben-Norris** [comment]
Hi! Thanks for letting me know. It is fixed now and should work in versions 2.90 - 2.93.
